### ISSUE TITLE
Can fit covert cyno to battlecruisers

### ISSUE THREAD

**Issue by alexanderbh** [mrdepth/libdgmpp#8]
Steps to reproduce:
- Fit a covert cynosural field generator I to a drake

I expected it to fail.

But it actually get added and used for calculating fitting data.

**Comment by evanova** [comment]
(This is relevant using the Java wrapper)

I am experiencing some weird behaviour with canFit(Module*) vs addModule(TypeID).
I noticed that Ship.addModule while supposedly checking for Ship.canFit seems to add modules anyway.

I created a Ship.canFit(TypeID) and experimented a little:

- Given a type ID that would not fit (because there isn't more slot space available for example).

- Calling Ship.canFit(TypeID) will return false.

- Calling Ship.addModule(TypeID) will return a Module; this module is added even though there isn't any slot space left.

Here's the addition to Ship.hpp I did

`
    	bool canFit (TypeID typeID) { LOCK(this); return canFit_(Module::Create(typeID).get()); }
`

**Comment by mrdepth** [comment]
The problem was in the wrong order of 'addModule' arguments.
Fixed.

**Comment by evanova** [comment]
Fix Verified.

**Comment by mrdepth** [comment]
Done
